# -*- coding: utf-8 -*-
"""project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RCLmy2o3opYIO6uw6s7SZxock8BHRjYT
"""



# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
print("Setup Complete")

cancer_filepath ="/content/world_smoking_history_1924_2023 (1).csv"

cancer_data= pd.read_csv(cancer_filepath)

sns.lineplot(data=cancer_data);

plt.figure(figsize=(10, 6))
sns.histplot(cancer_data['Male_Smokers_Percentage'], kde=True, color='blue', label='Male Smokers', bins=30, alpha=0.5)
sns.histplot(cancer_data['Female_Smokers_Percentage'], kde=True, color='red', label='Female Smokers', bins=30, alpha=0.5)
plt.title('Overlapping Histograms of Male and Female Smokers')
plt.xlabel('Number of Smokers in Percentage')
plt.ylabel('Frequency')
plt.legend()
plt.show()

g = sns.FacetGrid(cancer_data, col="Country", col_wrap=4, height=4)
g.map(sns.histplot, "Male_Smokers_Percentage", kde=True, bins=30)
g.add_legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns


# Set the width and height of the figure
plt.figure(figsize=(14, 6))

# Add title
plt.title("Comparison of Smokers Percentage and Average Cigarettes Per Day")

# Plot percentages of male and female smokers
sns.lineplot(data=cancer_data, x='Year', y='Male_Smokers_Percentage', label="Male Smokers (%)")
sns.lineplot(data=cancer_data, x='Year', y='Female_Smokers_Percentage', label="Female Smokers (%)")

# Create a second y-axis for the average cigarettes per day
ax1 = plt.gca()
ax2 = ax1.twinx()

sns.lineplot(data=cancer_data, x='Year', y='Average_Cigarettes_Per_Day', label="Avg Cigarettes Per Day", ax=ax2, color="green")

# Add labels for the axes
ax1.set_xlabel("Year")
ax1.set_ylabel("Smokers Percentage")
ax2.set_ylabel("Average Cigarettes Per Day")

# Add legends
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')

# Display the plot
plt.show()